[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gptgitassist"
version = "0.0.1"
description = "FLH CoreTech Team Assistant CLI Python Package."
readme = "README.md"
authors = [
    {name = "FLHCore", email = "operation@flh.com.tw"}
]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
"Homepage" = "https://www.flh.com.tw"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["find:"]
install-requires = [
    # 以字符串列表的形式添加你的依赖，例如:
    "click>=8.1.7",
    # 将`requirements.txt`中的每一个依赖项都转换为上面的形式
]
python-requires = ">=3.7"

[project.scripts]
create-git-diff = "create_git_diff_for_gpt:main"
